name: Export Web PCK

on: [push, pull_request]

jobs:
  export-web-pck:
    name: Web Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:mono-3.5.2
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Export Templates
        run: |
          mkdir -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

      - name: Create Export Folder
        run: mkdir -p web_export

      - name: Web Build
        run: |
          cd ${{ github.workspace }}
          godot --headless --verbose --export-release "HTML5" web_export/index.html

      - name: Zip Export Folder
        run: zip -r web_export.zip web_export/

      - name: Upload Zipped Artifact
        uses: actions/upload-artifact@v3
        with:
          name: web_export.zip
          path: web_export.zip
