name: Export Web PCK

on: [push, pull_request]

jobs:
  export-web-pck:
    name: Web Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:mono-3.5.2
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Export Folder
        run: mkdir -p export

      - name: Web Build
        run: |
          godot --headless --verbose --import --editor --quit-after 20
          godot --headless --verbose --import --quit-after 42 --export-release "HTML5" export/index.html

      - name: Zip Export Folder
        run: zip -r export.zip export/

      - name: Upload Zipped Artifact
        uses: actions/upload-artifact@v3
        with:
          name: export.zip
          path: export.zip
