name: Export Web PCK

on: [push, pull_request]

jobs:
  export-web-pck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull Docker image
        run: docker pull robpc/godot-headless:3.5.3-html

      - name: Create Export Folder
        run: mkdir -p export

      - name: Export Web PCK
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/project \
            robpc/godot-headless:3.5.3-html \
            --path /project --export HTML5 export/index.pck

      - name: Zip Export Folder
        run: zip -r export.zip export/

      - name: Upload Zipped Artifact
        uses: actions/upload-artifact@v3
        with:
          name: export.zip
          path: export.zip
